app:
  datasource:
    cop:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5454/cop
      username: postgres
      password: postgres

spring:
  liquibase:
    enabled: off
