spring:
  application:
    name: cop
  jpa:
    generate-ddl: true  # "off" для отмены авто-генерации БД через "JPA"
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  liquibase:
    enabled: off
    change-log: classpath:db/changelog/cop-db-master.xml

app:
  datasource:
    cop:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/cop
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}


logging:
  level:
    org:
      hibernate:
        SQL: ERROR
      type:
        descriptor:
          sql:
            BasicBinder: ERROR
      springframework:
        jdbc:
          core:
            JdbcTemplate: ERROR
            StatementCreatorUtils: ERROR

springdoc:
  packagesToScan: com.example.trafficcop
  swagger-ui:
    disable-swagger-default-url: true
